config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'

  resources :articles, only: [:index, :show]
  resources :categories, only: [] do
    resources :articles, only: [:index, :show]
  end
  get '/most_viewed' => 'articles#most_viewed', as: 'most_viewed'

  namespace :admin do
    root to: 'home#index'

    resources :categories, except: :show
    resources :articles do
      post :upload_attachment, on: :member
    end
  end

  devise_for :admins

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable :registerable, :recoverable,
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]
  include SlugHelper

  is_impressionable counter_cache: true

  belongs_to :category
  has_many :attachments, dependent: :destroy


  has_attached_file :main_image, styles: {medium: '500x500>', thumb: '100x100>'}
  validates_attachment_content_type :main_image, content_type: /\Aimage\/.*\z/

  scope :published, -> { where(published: true) }

  def next
    self.class.published.where("id > ?", id).first
  end

  def previous
    self.class.published.where("id < ?", id).last
  end
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :article

  has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
  include SlugHelper
end

app/models/concerns/slug_helper.rb
module SlugHelper
  def should_generate_new_friendly_id?
    true
  end

  def normalize_friendly_id(text)
    text.to_slug.transliterate(:ukrainian).normalize.to_s
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::BaseController
  before_action :set_article, only: [:create, :show, :edit, :update, :destroy, :upload_attachment]
  before_action :set_categories, only: [:new, :create, :edit, :update]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.create(title: "#{t(:new_article_form)} #{Date.current}", content: '', category: Category.first)
    redirect_to edit_admin_article_url(@article)
  end

  def edit
  end

  def create
    if @article.update(article_params)
      redirect_to edit_admin_article_url(@article), notice: t(:article_was_successfully_created)
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      redirect_to edit_admin_article_url(@article), notice: t(:article_was_successfully_updated)
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to admin_articles_url, notice: t(:article_was_successfully_destroyed)
  end

  def upload_attachment
    @attachment = @article.attachments.create(image: params[:file])
    respond_to do |format|
      format.json { render :json => { status: 'OK', link: @attachment.image.url}}
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def set_categories
    @categories = Category.all
  end

  def article_params
    params.require(:article).permit(:title, :content, :category_id, :main_image, :published)
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_admin!
  layout 'admin'
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to edit_admin_category_url(@category), notice: t(:category_was_successfully_created)
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to edit_admin_category_url(@category), notice: t(:category_was_successfully_updated)
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to admin_categories_url, notice: t(:category_was_successfully_destroyed)
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::BaseController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout :layout_by_resource
  protected

  def layout_by_resource
    if devise_controller?
      'devise'
    else
      'application'
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_search

  def index
    @articles = Article.published
    if params[:q].present?
      @articles = @search.result
    end

    if params[:category_id].present?
      @category = Category.find(params[:category_id])
      @articles = @articles.where(category: @category.id)
    end
    @articles = @articles.order(created_at: :desc).page(params[:page]).per(9)
  end

  def most_viewed
    @articles = Article.published.order('impressions_count DESC').page(params[:page]).per(9)
    render :index
  end

  def show
    @article = Article.find(params[:id])
    @latest_articles = Article.published.order(created_at: :desc).first(5)
    @most_viewed = Article.published.order('impressions_count DESC').first(5)
    impressionist(@article, '', unique: [:ip_address])
  end

  private

  def set_search
    @categories = Category.all
    @search = Article.published.ransack(params[:q])
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  before_action :set_search

  def not_found
    render(:status => 404)
  end

  def internal_server_error
    render(:status => 500)
  end

  private

  def set_search
    @categories = Category.all
    @search = Article.published.ransack(params[:q])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_time(time)
    time.strftime('%e %b %Y %H:%M:%S')
  end

  def active_class(link_path)
    request.url.include?(link_path) ? 'active' : ''
  end
end

app/views/admin/articles/_form.html.slim
= form_for [:admin, @article], data: {id: @article.id} do |f|
  - if @article.errors.any?
    #error_explanation
      h3
        = pluralize(@article.errors.count, 'error')
        |  prohibited this article from being saved:
      ul
        - @article.errors.full_messages.each do |message|
          li
            = message
  .form-group
    = f.label :title, t(:title)
    br
    = f.text_field :title, class: 'form-control', placeholder: t(:enter_article_title), required: true
  .form-group
    = f.label :main_image, t(:main_image)
    br
    = f.file_field :main_image
  - if @article.main_image.present?
    .row
      .col-sm-4
        = image_tag @article.main_image.url(:medium), class: 'img-responsive'
  .form-group
    = f.label :content, t(:content)
    br
    = f.text_area :content, class: 'form-control', placeholder: t(:enter_content), required: true
  .form-group
    = f.label :category, t(:category)
    br
    = f.select :category_id, options_for_select(@categories.collect {|c| [c.name, c.id]}, @article.category_id), { prompt: t(:select_a_category) }, { required: true, class: 'form-control' }
  .form-group
    .checkbox
      = f.label :published do
        = f.check_box :published
        = t(:publish)
  .form-group.actions
    = f.submit t(:submit), :class => 'btn btn-lg btn-success btn-block'


- content_for(:extra_scripts) do
  javascript:
    $(document).ready(function () {
      $('#article_content').summernote({
          lang: 'uk-UA',
          height: 200,
          toolbar: [
              ['style', ['style']],
              ['font', ['bold', 'italic', 'underline', 'strikethrough', 'superscript', 'subscript', 'clear']],
              ['fontname', ['fontname']],
              ['fontsize', ['fontsize']],
              ['color', ['color']],
              ['para', ['ul', 'ol', 'paragraph']],
              ['height', ['height']],
              ['table', ['table']],
              ['insert', ['link', 'picture', 'video', 'hr']],
              ['help', ['fullscreen', 'codeview', 'undo', 'redo', 'help']]
          ],
          callbacks: {
              onImageUpload: function(files) {
                  return sendFile(files[0], $(this));
              }
          }
      });

      $('.dropdown-toggle').dropdown();

      function sendFile(file, toSummernote) {
          var id = $("form").data("id");
          var data;
          data = new FormData;
          data.append('file', file);
          return $.ajax({
              data: data,
              type: 'POST',
              url: Routes.upload_attachment_admin_article_path(id, {format: 'json'}),
              cache: false,
              contentType: false,
              processData: false,
              success: function (data) {
                  return toSummernote.summernote("insertImage", data.link);
              }
          });
      };
    });

app/views/admin/articles/edit.html.slim
- content_for :panel_heading do
  = t(:edit_article)
= render 'form'

app/views/admin/articles/index.html.slim
- content_for(:page_header) do
  = link_to t(:new_article), new_admin_article_path, class: 'btn btn-success'
- content_for :panel_heading do
  = t(:articles)
p#notice
  = notice
table#articles.display.table[cellspacing="0" width="100%"]
  thead
    tr
      th[width="40%"]
        = t(:title)
      /th
      /  = t(:content)
      th
        = t(:category)
      th
        = t(:updated_at)
      th
        = t(:views_count)
      th
  tbody
    - @articles.each do |article|
      tr
        td
          = article.title
        /td
        /  = ActionView::Base.full_sanitizer.sanitize(article.content).truncate(50)
        td
          = article.category.name if article.category
        td
          = show_time(article.updated_at)
        td
          = article.impressionist_count(:filter=>:ip_address)
        td.action-buttons
          = link_to article, class: 'btn btn-success', target: :_blank do
            i.fa.fa-eye
          = link_to edit_admin_article_path(article), class: 'btn btn-primary' do
            i.fa.fa-pencil
          = link_to admin_article_path(article), method: :delete, data: { confirm: t(:are_you_sure) }, class: 'btn btn-danger' do
            i.fa.fa-trash

- content_for(:extra_scripts) do
  javascript:
    $(document).ready(function () {
      $('#articles').DataTable({
        responsive: true,
        stateSave: true,
        order: [[ 2, "desc" ]],
        language: {
              "url": "//cdn.datatables.net/plug-ins/1.10.13/i18n/Ukrainian.json"
          }
      });
    });

app/views/admin/articles/new.html.slim
- content_for :panel_heading do
  = t(:create_new_article)
= render 'form'

app/views/admin/articles/show.html.slim
- content_for :panel_heading do
  = t(:article_preview)

p
  strong = t(:title)
  br
  = @article.title

p
  strong = t(:content)
  br
  =raw @article.content.split('<hr>')[0]

p
  strong = t(:category)
  br
  = @article.category.name

app/views/admin/categories/_form.html.slim
= form_for [:admin, @category] do |f|
  - if @category.errors.any?
    #error_explanation
      h3
        = pluralize(@category.errors.count, 'error')
        |  prohibited this category from being saved:
      ul
        - @category.errors.full_messages.each do |message|
          li
            = message
  .form-group
    = f.label :name, t(:name)
    br
    = f.text_field :name, class: 'form-control', placeholder: 'Enter category name...', required: true
  .form-group.actions
    = f.submit t(:submit), :class => 'btn btn-lg btn-success btn-block'

app/views/admin/categories/edit.html.slim
- content_for :panel_heading do
  = t(:edit_category)
= render 'form'

app/views/admin/categories/index.html.slim
- content_for(:page_header) do
  = link_to t(:new_category), new_admin_category_path, class: 'btn btn-success'
- content_for :panel_heading do
  = t(:categories)
p#notice
  = notice
table#categories.display.table[cellspacing="0" width="100%"]
  thead
    tr
      th
        = t(:name)
      th
  tbody
    - @categories.each do |category|
      tr
        td[width="70%"]
          = category.name
        td.action-buttons
          = link_to t(:edit), edit_admin_category_path(category), class: 'btn btn-primary'
          = link_to t(:destroy), admin_category_path(category), method: :delete, data: { confirm: t(:are_you_sure) }, class: 'btn btn-danger'

app/views/admin/categories/new.html.slim
- content_for :panel_heading do
  | Create new category
= render 'form'

app/views/admin/home/index.html.slim
//stats
.row
  .col-lg-6.col-md-6
    .panel.panel-primary
      .panel-heading
        .row
          .col-xs-3
            i.fa.fa-comments.fa-5x
          .col-xs-9.text-right
            .huge= Article.count
            div= t(:articles)
  .col-lg-6.col-md-6
    .panel.panel-green
      .panel-heading
        .row
          .col-xs-3
            i.fa.fa-tasks.fa-5x
          .col-xs-9.text-right
            .huge= Article.all.sum(:impressions_count)
            div= t(:views_count)

app/views/admin/shared/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    |  <div class="alert alert-
    = name.to_s == 'notice' ? 'success' : 'danger'
    | "> 
    button.close[type="button" data-dismiss="alert" aria-hidden="true"]
      | ×
    = content_tag :div, msg, :id => "flash_#{name}"

app/views/admin/shared/_nav_links_for_auth.html.slim
- if user_signed_in?
  li
    = link_to 'Edit account', edit_user_registration_path
  li
    = link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  li
    = link_to 'Sign in', new_user_session_path
  li
    = link_to 'Sign up', new_user_registration_path
- if user_signed_in?
  li
    = link_to 'Users', users_path

app/views/admin/shared/_navbar.html.slim
nav.navbar.navbar-default.navbar-static-top[role="navigation" style="margin-bottom: 0"]
  .navbar-header
    button.navbar-toggle[data-target=".navbar-collapse" data-toggle="collapse" type="button"]
      span.sr-only
        = t(:toggle_navigation)
      span.icon-bar
      span.icon-bar
      span.icon-bar
    = link_to t(:dashboard), admin_root_path, class: 'navbar-brand'
  ul.nav.navbar-top-links.navbar-right.pull-right
    li
      = link_to destroy_admin_session_path, :method => 'delete' do
        i.fa.fa-sign-out
  .navbar-default.sidebar[role="navigation"]
    .sidebar-nav.navbar-collapse
      ul#side-menu.nav.in
        li
          = link_to admin_articles_path do
            i.fa.fa-bar-chart-o.fa-fw
            = t(:articles)
        li
          = link_to admin_categories_path do
            i.fa.fa-bar-chart-o.fa-fw
            = t(:categories)

app/views/admin/shared/_title.html.slim
br
.row
  .col-lg-12.pull-right
    = content_for?(:page_header) ? yield(:page_header) : ''

app/views/articles/_article_sidebar.html.slim
.widget
  .heading-title-alt.text-left.heading-border-bottom
    h6.text-uppercase =t(:latest_articles)
  ul.widget-latest-post
    - @latest_articles.each do |article|
      li
        .thumb
          - if article.main_image.present?
            = image_tag article.main_image.url(:thumb)
        .w-desk
          = link_to article.title, article
          = show_time(article.updated_at)
.widget
  .heading-title-alt.text-left.heading-border-bottom
    h6.text-uppercase =t(:most_viewed)
  ul.widget-latest-post
    - @most_viewed.each do |article|
      li
        .thumb
          - if article.main_image.present?
            = image_tag article.main_image.url(:thumb)
        .w-desk
          = link_to article.title, article
          = show_time(article.updated_at)

.widget
  .heading-title-alt.text-left.heading-border-bottom
    h6.text-uppercase =t(:categories)
  ul.widget-category
    - @categories.all.each do |category|
      li
        = link_to category.name, category_articles_path(category)

app/views/articles/index.html.slim
- breadcrumb :category, @category
/- breadcrumb :search
.container
  .row
    .portfolio.portfolio-with-title.portfolio-masonry.blog-m.col-3.gutter
      - @articles.each do |article|
        .portfolio-item
          - if article.main_image.present?
            .thumb
              = image_tag article.main_image.url(:medium)
              .portfolio-hover
                .action-btn
                  = link_to article do
                    i.icon-basic_link
          .portfolio-title
            h4
              = link_to article.title, article
            .date
              = show_time(article.updated_at)
            p = ActionView::Base.full_sanitizer.sanitize(article.content).truncate(150)
            .m-top-20.m-bot-20
              = link_to t(:read_more), article, class: 'btn btn-extra-small btn-dark-border btn-transparent'

    .col-md-12
      /! pagination
      .text-center
        = paginate @articles

    /! feature border box start
    - if @articles.empty?
      .feature-box-grid
        .heading-title.text-center
          h3.text-uppercase =t(:content_not_found)

app/views/articles/show.html.slim
- set_meta_tags og: { title: @article.title,
                      type: 'article',
                      url: request.original_url,
                      image: @article.main_image.url,
                      description: ActionView::Base.full_sanitizer.sanitize(@article.content).truncate(150),
                    },
                  description: ActionView::Base.full_sanitizer.sanitize(@article.content).truncate(150),
                  image_src: @article.main_image.url

- breadcrumb :category, @article.category
.page-content
  .container
    .row
      .col-md-8
        /! classic image post
        .blog-classic
          .blog-post
            - if @article.main_image.present?
              .full-width
                = image_tag @article.main_image.url
            h1.text-uppercase
              = title @article.title
            ul.post-meta
              li
                i.fa.fa-folder-open
                = link_to @article.category.name, category_articles_path(@article.category)
              li
                i.fa.fa-clock-o
                = show_time(@article.updated_at)
            p
              = raw @article.content

        .pagination-row
          .pagination-post
            .prev-post
              - if @article.previous
                = link_to article_path(@article.previous) do
                  .arrow
                    i.fa.fa-angle-double-left
                  .pagination-txt
                    span =t(:previous_post)
              - else
                a href="#"
                  .arrow
                    i.fa.fa-angle-double-left
                  .pagination-txt
                    span =t(:previous_post)
            .post-list-link
              = link_to root_path do
                i.fa.fa-home
            .next-post
              - if @article.next
                = link_to article_path(@article.next) do
                  .arrow
                    i.fa.fa-angle-double-right
                  .pagination-txt
                    span =t(:next_post)
              - else
                a href="#"
                  .arrow
                    i.fa.fa-angle-double-right
                  .pagination-txt
                    span =t(:next_post)

      .col-md-4
        = render partial: 'article_sidebar'

app/views/layouts/admin.html.slim
doctype html
html
  head
    title
      = t(:news_portal)
    = csrf_meta_tags
    = stylesheet_link_tag 'admin', media: 'all'
  body
    #wrapper
      = render 'admin/shared/navbar'
    #page-wrapper
      = render 'admin/shared/title'
      br
      div
        = render 'admin/shared/messages'
      - if current_page?(admin_root_path)
        = yield
      - else
        div.panel.panel-default
          .panel-heading
            = content_for?(:panel_heading) ? yield(:panel_heading) : t(:dashboard)
          .panel-body
            = yield
  = javascript_include_tag 'admin'
  = content_for?(:extra_scripts) ? yield(:extra_scripts) : nil

app/views/layouts/application.html.slim
doctype html
html
  head
    = display_meta_tags site: 'Рідне місто'
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
  body
    #tb-preloader
      .tb-preloader-wave
    /! preloader end
    .wrapper
      /! header start
      header.l-header
        .l-navbar.l-navbar_expand.l-navbar_t-light.js-navbar-sticky
          .container-fluid
            nav.menuzord.js-primary-navigation aria-label=('Primary Navigation') role="navigation"
              /! logo start
              = link_to root_path, class: 'logo-brand' do
                = image_tag asset_path('logo.png')
                /img.retina alt="Massive" src="/assets/logo.png"
              /! logo end
              /! mega menu start
              ul.menuzord-menu.menuzord-right.c-nav_s-bg
                li
                  = link_to t(:home), root_path
                li
                  a href="#" =t(:categories)
                  ul.dropdown
                    - @categories.all.each do |category|
                      li
                        = link_to category.name, category_articles_path(category)
                li
                  = link_to t(:most_viewed), most_viewed_path
                li
                  a href="javascript:void(0)"
                    i.fa.fa-search
                    = t(:search)
                  .megamenu.megamenu-quarter-width.navbar-search
                    = search_form_for @search do |f|
                      = f.search_field :title_or_content_cont, class: 'form-control'
                        /span.input-group-btn
                        /  = f.submit class: 'btn btn-default'
                    /form role="searchform"
                    /  input.form-control placeholder=("Search Here") type="text" /

      - if current_page?(root_path)
        /.banner-state.vertical-align.banner-01.height-600
          .container-mid
            .container
              .row
                .col-md-8
                  .banner-title
                    /h1.text-uppercase Рідне місто
      - elsif breadcrumbs.links.any?
        section.page-title
          .container
            = raw(breadcrumbs style: :bootstrap)

      section.body-content
        = yield
      /! body content end
      /! footer start 1
      footer#footer.gray.text-center.short-pad.footer-5
        .container-
          = link_to root_path, class: 'footer-logo' do
            = image_tag asset_path('logo.png'), style:('height: 80px; width: auto;')
            /img.retina alt="" src="/assets/logo.png" style=('height: 100px; width: auto;')
          .social-link.circle.m-top-50.m-bot-50
            a href="#"
              i.fa.fa-facebook
            a href="#"
              i.fa.fa-twitter
            a href="#"
              i.fa.fa-dribbble
            a href="#"
              i.fa.fa-google-plus
            a href="#"
              i.fa.fa-behance
          .copyright-sub-title.text-uppercase.border-top
            | © Copyright 2017 "Рідне місто". All right reserved

    = javascript_include_tag 'application'

app/views/layouts/devise.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Admin Panel'
    = stylesheet_link_tag 'admin'
    = csrf_meta_tags
  body
    .container
      .row
        .col-md-4.col-md-offset-4[style="text-align:center;"]
          h1
            = t(:dashboard)
      .row
        .col-md-4.col-md-offset-4
          .login-panel.panel.panel-default
            .panel-heading
              h3.panel-title
                = t('devise.sessions.new.sign_in')
            .panel-body
              = yield
  = javascript_include_tag 'admin'